package de.pat.fxsettings.moduletypes;

public enum FXModuleType
{
    CHECK_BOX, COLOR_PICKER, COMBO_BOX, DATE_PICKER, DOUBLE_FIELD, INTEGER_FIELD, PASSWORD_FIELD, SLIDER, TEXT_AREA, TEXT_FIELD, TOGGLE_BUTTON, CHECKLIST_VIEW

}
